from __future__ import annotations

from datetime import datetime

from app.repositories import repository


def article_markdown(article_id):
    article = repository.get_article(article_id)
    note = repository.get_note(article_id)
    return "\n\n".join(
        [
            f"# {article['title']}",
            f"Source: {article['url']}",
            article.get("cleaned_markdown") or article.get("summary") or "",
            "## Notes",
            note["content_markdown"],
        ]
    )


def articles_markdown(article_ids):
    return "\n\n---\n\n".join(article_markdown(article_id) for article_id in article_ids)


def batch_digest_export(payload):
    export_time = datetime.now().astimezone().replace(microsecond=0)
    digest_title = export_time.strftime("Digest %y-%m-%d")
    filename = export_time.strftime("%Y-%m-%d-digest.md")

    entries = []
    exported_article_ids = []
    skipped_article_ids = []

    for article_id in payload.article_ids:
        try:
            article = repository.get_article(article_id)
        except ValueError:
            skipped_article_ids.append(article_id)
            continue

        title = _normalize_required_text(article.get("title"))
        url = _normalize_required_text(article.get("url"))
        if not title or not url:
            skipped_article_ids.append(article_id)
            continue

        author = _normalize_optional_text(article.get("author")) or _normalize_optional_text(article.get("feed_title")) or ""
        note = repository.get_note(article_id)
        summary_record = repository.get_latest_ai_result(article_id, "summary") if payload.include_summary else None

        entries.append(
            {
                "title": title,
                "author": author,
                "url": url,
                "summary": _normalize_optional_text(summary_record["result"]) if summary_record else None,
                "note": _normalize_optional_text(note.get("content_markdown")) if payload.include_note else None,
            }
        )
        exported_article_ids.append(article_id)

    if not entries:
        raise ValueError("No exportable articles were found in the selected batch.")

    return {
        "digest_title": digest_title,
        "filename": filename,
        "markdown": _render_batch_digest_markdown(digest_title, filename, export_time, entries),
        "exported_article_ids": exported_article_ids,
        "skipped_article_ids": skipped_article_ids,
    }


def _render_batch_digest_markdown(digest_title: str, filename: str, export_time: datetime, entries: list[dict[str, str | None]]) -> str:
    slug = filename[:-3] if filename.endswith(".md") else filename
    lines = [
        "+++",
        f"date = '{export_time.isoformat()}'",
        "draft = false",
        f"title = '{_escape_toml_string(digest_title)}'",
        f"slug = '{slug}'",
        "+++",
        "",
    ]

    for index, entry in enumerate(entries):
        if index:
            lines.append("")
        lines.extend(
            [
                f"## {entry['title']}",
                "",
                f"**Source**: [{entry['url']}]({entry['url']})",
                f"**Author**: {entry['author']}",
            ]
        )

        if entry["summary"]:
            lines.extend(
                [
                    "",
                    *_blockquote_lines(entry["summary"]),
                    ">",
                    "> - generated by RSSReader Summary Agent",
                ]
            )

        if entry["note"]:
            lines.extend(
                [
                    "",
                    "**Note**:",
                    entry["note"],
                ]
            )

        lines.append("")

    return "\n".join(lines).strip()


def _blockquote_lines(text: str) -> list[str]:
    return [f"> {line}" if line else ">" for line in text.splitlines()]


def _normalize_required_text(value: str | None) -> str:
    return (value or "").strip()


def _normalize_optional_text(value: str | None) -> str | None:
    normalized = _normalize_required_text(value)
    return normalized or None


def _escape_toml_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")
